### ISSUE TITLE
rds multiaz not working

### ISSUE THREAD

**Issue by austin-ralls-cs** [CarveSystems/scanamabob#37]
I'm not sure if the test isn't working or if I'm misunderstanding something.
![multiaz](https://user-images.githubusercontent.com/34071858/91585461-15ac6180-e922-11ea-9ded-2b919c40e7d7.png)
but when I add in debugging statements, the API really is returning `MultiAZ=False` for those instances.

could it be some confusion between clusters and instances?

**Comment by meadori-cs** [comment]
Good catch!  It is a confusion between clusters and instances.  Clusters can have properties by the same name (e.g. `MultiAZ`) that take precedence over the instance property.

Working on a fix.
